[[characters]]
name = "Ember"
description = "Your helpful guide to The Late Shows."

model_name = "ember"

text_colour = { r = 0, g = 0, b = 0}
background_colour = { r = 255, g = 255, b = 0 }
border_colour = { r = 169, g = 169, b = 169 }

opening_lines = [
  "Hey, there!",
  "Hi",
  "Hello",
  "Excuse me.",
]

[[characters]]
name = "Mia"
description = "A member of Maker Space that nobody knows exists."

model_name = "mia"

text_colour = { r = 255, g = 255, b = 255 }
background_colour = { r = 255, g = 105, b = 180 }
border_colour = { r = 100, g = 149, b = 237 }

opening_lines = [
  "Hey, there!",
  "Hi",
  "Hello",
  "Um, hi...",
  "Excuse me.",
]

[[characters]]
name = "Vi"
description = "A relentless, battle-scarred enforcer from Zaun."

model_name = "vi"

text_colour = { r = 240, g = 255, b = 245}
background_colour = { r = 220, g = 20, b = 60 }
border_colour = { r = 205, g = 92, b = 92 }

opening_lines = [
  "Hey, there!",
  "Hi",
  "Hello",
  "Excuse me.",
]

[[characters]]
name = "Marisa"
description = "A powerful, mischievous magician from Gensokyo."

model_name = "marisa"

text_colour = { r = 0, g = 0, b = 0}
background_colour = { r = 255, g = 215, b = 0 }
border_colour = { r = 211, g = 211, b = 211 }

opening_lines = [
  "Hey, there!",
  "Hi",
  "Hello",
  "Sup!",
  "Excuse me.",
]

[[characters]]
name = "GLaDOS"
description = "Orchastrator of the Aperture Science Enrichment Center."

model_name = "glados"

text_colour = { r = 240, g = 255, b = 245}
background_colour = { r = 50, g = 110, b = 120 }
border_colour = { r = 0, g = 255, b = 255 }

opening_lines = [
  "Hi",
  "Hello",
  "Excuse me.",
]
