---
name: Host Software

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/host-software.yml'
      - 'devenv.*'
      - 'icd/**'
      - 'host-software/**'
  pull_request:
    paths:
      - '.github/workflows/host-software.yml'
      - 'devenv.*'
      - 'icd/**'
      - 'host-software/**'

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Clippy
        shell: devenv shell bash -- -e {0}
        run: |
          set -x
          cd ./host-software
          cargo clippy -- -Dwarnings

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - quality

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
        shell: devenv shell bash -- -e {0}
        run: |
          set -x
          cd ./host-software
          cargo build --release

      - name: Build (aarch64)
        shell: devenv shell bash -- -e {0}
        run: |
          set -x
          cd ./host-software
          cross build --release --target aarch64-unknown-linux-gnu
